version: '3.8'

services:
  web:
    build: .
    ports:
      - "${PORT:-8040}:80"
    volumes:
      - ./src:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: database     # Replace with your database name
      POSTGRES_USER: postgres        # Replace with your database user
      POSTGRES_PASSWORD: postgres # Replace with your database password
    ports:
      - "${PGPORT:-5432}:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
