version: '3.8'

services:
  web:
    build: .
    container_name: php_apache_server
    ports:
      - "${PORT:-8040}:80"
      - "${PORT_SSL:-8443}:443"
    volumes:
      - ./src:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
