version: '3.8'

services:
  web:
    build: .
    ports:
      - "${PORT:-8040}:80"
    volumes:
      - ./src:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}   # Nama database
      POSTGRES_USER: ${POSTGRES_USER}   # Mengambil username dari .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Mengambil password dari .env
    ports:
      - "${PGPORT:-5432}:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
